# Numpy

In [1]:
import numpy as np

In [3]:
vector = np.array([0,1,2,3,4,5])
print(vector)

[0 1 2 3 4 5]


In [6]:
vectorDos = np.array([1,2,3,4,5],dtype=np.float32)
print(vectorDos)

vector.dtype = np.float16
print(vector)

vectorTres = np.array([1,2,3,4,5])
vectorTres = vectorTres.astype(np.float32)
print(vectorTres)

[1. 2. 3. 4. 5.]
[0.0e+00 0.0e+00 0.0e+00 0.0e+00 6.0e-08 0.0e+00 0.0e+00 0.0e+00 1.2e-07
 0.0e+00 0.0e+00 0.0e+00 1.8e-07 0.0e+00 0.0e+00 0.0e+00 2.4e-07 0.0e+00
 0.0e+00 0.0e+00 3.0e-07 0.0e+00 0.0e+00 0.0e+00]
[1. 2. 3. 4. 5.]


In [8]:
print(vectorTres[3])

4.0


In [10]:
vectorCuatro = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print(vectorCuatro[0:8:2])

[0 2 4 6]


In [22]:
a = np.array([0,1,2])
b = np.array([0,-1,-3])
c = np.array([1,1,1])
print(a + b)
print(a - b)
print(a * b)
print(a / c)
print(2 * a)
demo = a >= 1
print(demo)
print(a ** a)

[ 0  0 -1]
[0 2 5]
[ 0 -1 -6]
[0. 1. 2.]
[0 2 4]
[False  True  True]
[1 1 4]


In [30]:
print(np.linspace(0,15,15))
print(np.arange(0,15,1))


[ 0.          1.07142857  2.14285714  3.21428571  4.28571429  5.35714286
  6.42857143  7.5         8.57142857  9.64285714 10.71428571 11.78571429
 12.85714286 13.92857143 15.        ]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [43]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
a = np.arange(0,16,1)
print(matrix)
print(matrix.shape)
print(a.shape)
nueva = matrix.reshape(9,)
print(nueva)
b = a.reshape(1,16)
print(b)
print("------------")
mt1=[[34,3],[67,7]]
mt2=[[11,2],[78,3]]
mt3=[[23,32],[90,1]]
arr1=np.array([mt1,mt2,mt3])
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(16,)
[1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]]
------------
[[[34  3]
  [67  7]]

 [[11  2]
  [78  3]]

 [[23 32]
  [90  1]]]


In [51]:
m = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m.shape)
c1 = m[:2,1:3]
c2 = m[2:,:]
print(c2.shape)
print(c2[0][1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
(1, 3)
8


In [53]:
A = np.array([[2,-1],[1,3]])
b = np.array([3,5])
c = np.linalg.solve(A, b)
print(c)
print(A@c)

[2. 1.]
[3. 5.]
