# <font color="darkblue">IMPORT</font>

In [63]:
import numpy as np
import math

# <font color="darkblue"> Ejercicio Dos Uno</font>

In [64]:
A = np.array([[1,4],[-1,3],[2,-9]])
cero = np.zeros((3,2))

## <font color="gold">a) A + 0 = A - 0 = A</font>

In [67]:
print(" A + 0 ".center(30,"*"))
r = A + 0
print(r)
print(" A - 0 ".center(30,"*"))
r = A - 0
print(r)

*********** A + 0 ************
[[ 1  4]
 [-1  3]
 [ 2 -9]]
*********** A - 0 ************
[[ 1  4]
 [-1  3]
 [ 2 -9]]


## <font color="gold">b) A - A = 0</font>

In [66]:
r = A - A
print(r)

[[0 0]
 [0 0]
 [0 0]]


# <font color="darkblue">Ejercicio Dos Dos</font>

In [94]:
A = np.array([[3,0],[-1,5]])
B = np.array([[4,-2,1],[0,2,3]])

## <font color="gold">a) A + 3B</font>

Al tener 2 matrices de diferentes dimensiones, no es posible realizar la operación de suma, sin embargo, si podemos hacer el producto de la matriz "B" por el número correspondiente (3).
Las matrices están descritas de la siguiente forma:
- A = A_2x2
- B = B_2x3
Lo que nos quedaría como:
- A + B = A_2X2 + B_2x3

Esto nos indica que una de las únicas operaciones posibles entre estas dos es un producto matricial.

In [72]:
producto = 3 * B
print(C)
try:
    r = A + producto
    print(r)
except ValueError:
    print("No es posible realizar la operación")

[[12 -6  3]
 [ 0  6  9]]
No es posible realizar la operación


<font color="red"><b>POSIBLE SOLUCIÓN</b></font>

In [98]:
C = 3 * B # Matriz para multiplicar 3 * B
D = np.array([[1,1,1],[1,1,1]]) # Matriz para convertir A de (2x2) a (2x3)
E = C * B # Producto de 3 * B
F = A@D # Producto para la redimensionamiento de A
r = F + E # Realizamos la suma
print(r)

[[51 15  6]
 [ 4 16 31]]


## <font color="gold">b) AB</font>

In [12]:
r = A@B
print(r)

[[12 -6  3]
 [-4 12 14]]


## <font color="gold">c) A^3</font>

In [62]:
r = np.linalg.matrix_power(A,3)
print(r)

[[ 27   0]
 [-49 125]]


## <font color="gold">d) B^2</font>

In [81]:
try:
    r = np.linalg.matrix_power(B,2)
    print(r)
except Exception:
    print("Las matriz no es cuadrada")

Las matriz no es cuadrada


## <font color="gold">e) (5A)B</font>

In [110]:
r = (5*A)@B
print(r)

[[ 60 -30  15]
 [-20  60  70]]


# <font color="darkblue">Ejercicio Dos Tres</font>

In [82]:
restaurantes=np.array([[30,15,4],[25,18,8]])
tiendas=np.array([[1.2,2.2,4.5],[1.3,2.1,4.6]])
print(" Tiendas ".center(30,"*"))
print(tiendas.T)
costoPorTienda=restaurantes@tiendas.T
print(" Costo por Tienda ".center(30,"*"))
print(costoPorTienda)
print(" Elección ".center(30,"*"))
print("Tienda 1", (costoPorTienda[0,0]+costoPorTienda[1,0]))
print("Tienda 2", (costoPorTienda[0,1]+costoPorTienda[1,1]))

********** Tiendas ***********
[[1.2 1.3]
 [2.2 2.1]
 [4.5 4.6]]
****** Costo por Tienda ******
[[ 87.   88.9]
 [105.6 107.1]]
********** Elección **********
Tienda 1 192.6
Tienda 2 196.0


# <font color="darkblue">Ejercicio Dos Cuatro</font>

In [134]:
productos = np.array([[200,75],[150,100],[100,125]])
transportes = np.array([[1.50,1.00,2.00],[1.75,1.50,1.00]])
costoPorTransporte = productos.T @ transportes.T
print(" Costo de almacen por transporte ".center(60,"*"))
print(f"Almacen 1:\t(Camión){costoPorTransporte[0,0]} \n\t\t(Tren){costoPorTransporte[1,0]}" )
print()
print(f"Almacen 2:\t(Camión){costoPorTransporte[0,1]} \n\t\t(Tren){costoPorTransporte[1,1]}" )
print(" Elección ".center(60,"*"))
print(f"Camión ${costoPorTransporte[0,0]+costoPorTransporte[1,0]}")
print(f"Tren ${costoPorTransporte[0,1]+costoPorTransporte[1,1]}")

************* Costo de almacen por transporte **************
Almacen 1:	(Camión)650.0 
		(Tren)462.5

Almacen 2:	(Camión)675.0 
		(Tren)406.25
************************* Elección *************************
Camión $1112.5
Tren $1081.25


# <font color="darkblue">Ejercicio Dos Cinco</font>

In [137]:
coeficientes = np.array([[3, 2, 0],[6, 4, 0],[1, 1, 0],[1, -4, 0],[2, -1, 2],[2, 3, -1],[1, 2, 2]])
independientes = np.array([6, -9, 3, 1, 3, 0, -12])
r = np.linalg.lstsq(coeficientes, independientes, rcond=None)[0]
print(f"x={r[0]} \ny={r[1]} \nz={r[2]}")

x=0.17024446400758358 
y=-1.173020925035551 
z=-2.205999864562878
